# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_controls.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TileMapWidget(object):
    def setupUi(self, TileMapWidget):
        TileMapWidget.setObjectName("TileMapWidget")
        TileMapWidget.resize(497, 397)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBoxCameras = QtWidgets.QComboBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCameras.sizePolicy().hasHeightForWidth())
        self.comboBoxCameras.setSizePolicy(sizePolicy)
        self.comboBoxCameras.setObjectName("comboBoxCameras")
        self.horizontalLayout_3.addWidget(self.comboBoxCameras)
        self.buttonConnectCamera = QtWidgets.QPushButton(self.dockWidgetContents)
        self.buttonConnectCamera.setObjectName("buttonConnectCamera")
        self.horizontalLayout_3.addWidget(self.buttonConnectCamera)
        self.buttonScanCameras = QtWidgets.QPushButton(self.dockWidgetContents)
        self.buttonScanCameras.setObjectName("buttonScanCameras")
        self.horizontalLayout_3.addWidget(self.buttonScanCameras)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCameraGamma = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelCameraGamma.setObjectName("labelCameraGamma")
        self.horizontalLayout.addWidget(self.labelCameraGamma)
        self.sliderCameraGamma = QtWidgets.QSlider(self.dockWidgetContents)
        self.sliderCameraGamma.setMinimum(0)
        self.sliderCameraGamma.setMaximum(500)
        self.sliderCameraGamma.setProperty("value", 100)
        self.sliderCameraGamma.setSliderPosition(100)
        self.sliderCameraGamma.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCameraGamma.setObjectName("sliderCameraGamma")
        self.horizontalLayout.addWidget(self.sliderCameraGamma)
        self.labelCameraGammaValue = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelCameraGammaValue.setObjectName("labelCameraGammaValue")
        self.horizontalLayout.addWidget(self.labelCameraGammaValue)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelFramerate = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelFramerate.setObjectName("labelFramerate")
        self.horizontalLayout_2.addWidget(self.labelFramerate)
        self.comboBoxFramerate = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBoxFramerate.setObjectName("comboBoxFramerate")
        self.horizontalLayout_2.addWidget(self.comboBoxFramerate)
        self.buttonSetFramerate = QtWidgets.QPushButton(self.dockWidgetContents)
        self.buttonSetFramerate.setObjectName("buttonSetFramerate")
        self.horizontalLayout_2.addWidget(self.buttonSetFramerate)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.labelVideoDisplay = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelVideoDisplay.setObjectName("labelVideoDisplay")
        self.gridLayout.addWidget(self.labelVideoDisplay, 3, 0, 1, 1)
        TileMapWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(TileMapWidget)
        QtCore.QMetaObject.connectSlotsByName(TileMapWidget)

    def retranslateUi(self, TileMapWidget):
        _translate = QtCore.QCoreApplication.translate
        self.buttonConnectCamera.setText(_translate("TileMapWidget", "connect"))
        self.buttonScanCameras.setText(_translate("TileMapWidget", "scan"))
        self.labelCameraGamma.setText(_translate("TileMapWidget", "Gamma"))
        self.labelCameraGammaValue.setText(_translate("TileMapWidget", "1"))
        self.labelFramerate.setText(_translate("TileMapWidget", "Framerate"))
        self.buttonSetFramerate.setText(_translate("TileMapWidget", "set framerate"))
        self.labelVideoDisplay.setText(_translate("TileMapWidget", "TextLabel"))
