# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_controls.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TileMapWidget(object):
    def setupUi(self, TileMapWidget):
        TileMapWidget.setObjectName("TileMapWidget")
        TileMapWidget.resize(497, 397)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.labelVideoDisplay = QtWidgets.QLabel(self.dockWidgetContents)
        self.labelVideoDisplay.setObjectName("labelVideoDisplay")
        self.gridLayout.addWidget(self.labelVideoDisplay, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 286, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.dockWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.comboBoxCameras = QtWidgets.QComboBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCameras.sizePolicy().hasHeightForWidth())
        self.comboBoxCameras.setSizePolicy(sizePolicy)
        self.comboBoxCameras.setObjectName("comboBoxCameras")
        self.buttonConnectCamera = QtWidgets.QPushButton(self.splitter)
        self.buttonConnectCamera.setObjectName("buttonConnectCamera")
        self.buttonScanCameras = QtWidgets.QPushButton(self.splitter)
        self.buttonScanCameras.setObjectName("buttonScanCameras")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        TileMapWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(TileMapWidget)
        QtCore.QMetaObject.connectSlotsByName(TileMapWidget)

    def retranslateUi(self, TileMapWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelVideoDisplay.setText(_translate("TileMapWidget", "TextLabel"))
        self.buttonConnectCamera.setText(_translate("TileMapWidget", "connect"))
        self.buttonScanCameras.setText(_translate("TileMapWidget", "scan"))
